// <auto-generated />
using System;
using Library.DomainData.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Library.DomainData.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    partial class StudentDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Library.TableData.Models.T_Class", b =>
                {
                    b.Property<int>("IDClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDClass");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            IDClass = 1,
                            NameClass = "11B"
                        },
                        new
                        {
                            IDClass = 2,
                            NameClass = "10B"
                        },
                        new
                        {
                            IDClass = 3,
                            NameClass = "12B"
                        },
                        new
                        {
                            IDClass = 4,
                            NameClass = "11A"
                        });
                });

            modelBuilder.Entity("Library.TableData.Models.T_Student", b =>
                {
                    b.Property<int>("IDStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IDClassStudent")
                        .HasColumnType("int");

                    b.Property<string>("NameStudent")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("T_ClassIDClass")
                        .HasColumnType("int");

                    b.HasKey("IDStudent");

                    b.HasIndex("IDClassStudent");

                    b.HasIndex("T_ClassIDClass");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            IDStudent = 1,
                            IDClassStudent = 1,
                            NameStudent = "Marry"
                        },
                        new
                        {
                            IDStudent = 2,
                            IDClassStudent = 2,
                            NameStudent = "Jsen"
                        },
                        new
                        {
                            IDStudent = 3,
                            IDClassStudent = 3,
                            NameStudent = "Cherry"
                        },
                        new
                        {
                            IDStudent = 4,
                            IDClassStudent = 4,
                            NameStudent = "Leon"
                        },
                        new
                        {
                            IDStudent = 5,
                            IDClassStudent = 1,
                            NameStudent = "Messis"
                        });
                });

            modelBuilder.Entity("Library.TableData.Models.T_Student", b =>
                {
                    b.HasOne("Library.TableData.Models.T_Class", null)
                        .WithMany()
                        .HasForeignKey("IDClassStudent")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Library.TableData.Models.T_Class", "T_Class")
                        .WithMany("T_Student")
                        .HasForeignKey("T_ClassIDClass");

                    b.Navigation("T_Class");
                });

            modelBuilder.Entity("Library.TableData.Models.T_Class", b =>
                {
                    b.Navigation("T_Student");
                });
#pragma warning restore 612, 618
        }
    }
}
